// Generated by gencpp from file struct_with_variable_length_vector/imgData.msg
// DO NOT EDIT!


#ifndef STRUCT_WITH_VARIABLE_LENGTH_VECTOR_MESSAGE_IMGDATA_H
#define STRUCT_WITH_VARIABLE_LENGTH_VECTOR_MESSAGE_IMGDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace struct_with_variable_length_vector
{
template <class ContainerAllocator>
struct imgData_
{
  typedef imgData_<ContainerAllocator> Type;

  imgData_()
    : upperLeft(0)
    , lowerRight(0)
    , color()
    , cameraID()  {
    }
  imgData_(const ContainerAllocator& _alloc)
    : upperLeft(0)
    , lowerRight(0)
    , color(_alloc)
    , cameraID(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _upperLeft_type;
  _upperLeft_type upperLeft;

   typedef int32_t _lowerRight_type;
  _lowerRight_type lowerRight;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _color_type;
  _color_type color;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cameraID_type;
  _cameraID_type cameraID;




  typedef boost::shared_ptr< ::struct_with_variable_length_vector::imgData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::struct_with_variable_length_vector::imgData_<ContainerAllocator> const> ConstPtr;

}; // struct imgData_

typedef ::struct_with_variable_length_vector::imgData_<std::allocator<void> > imgData;

typedef boost::shared_ptr< ::struct_with_variable_length_vector::imgData > imgDataPtr;
typedef boost::shared_ptr< ::struct_with_variable_length_vector::imgData const> imgDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::struct_with_variable_length_vector::imgData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::struct_with_variable_length_vector::imgData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace struct_with_variable_length_vector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'struct_with_variable_length_vector': ['/home/schwarmcyc/Documents/HackMD-tutorial/dit_ws/src/struct_with_variable_length_vector/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::struct_with_variable_length_vector::imgData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::struct_with_variable_length_vector::imgData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::struct_with_variable_length_vector::imgData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::struct_with_variable_length_vector::imgData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::struct_with_variable_length_vector::imgData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::struct_with_variable_length_vector::imgData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::struct_with_variable_length_vector::imgData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cbb96954cf5672df60c268734839f987";
  }

  static const char* value(const ::struct_with_variable_length_vector::imgData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcbb96954cf5672dfULL;
  static const uint64_t static_value2 = 0x60c268734839f987ULL;
};

template<class ContainerAllocator>
struct DataType< ::struct_with_variable_length_vector::imgData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "struct_with_variable_length_vector/imgData";
  }

  static const char* value(const ::struct_with_variable_length_vector::imgData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::struct_with_variable_length_vector::imgData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 upperLeft\n\
int32 lowerRight\n\
string color\n\
string cameraID\n\
";
  }

  static const char* value(const ::struct_with_variable_length_vector::imgData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::struct_with_variable_length_vector::imgData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.upperLeft);
      stream.next(m.lowerRight);
      stream.next(m.color);
      stream.next(m.cameraID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imgData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::struct_with_variable_length_vector::imgData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::struct_with_variable_length_vector::imgData_<ContainerAllocator>& v)
  {
    s << indent << "upperLeft: ";
    Printer<int32_t>::stream(s, indent + "  ", v.upperLeft);
    s << indent << "lowerRight: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lowerRight);
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.color);
    s << indent << "cameraID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cameraID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STRUCT_WITH_VARIABLE_LENGTH_VECTOR_MESSAGE_IMGDATA_H
