(cl:defpackage mastering_ros_demo_pkg-msg
  (:use )
  (:export
   "<LAYOUT>"
   "LAYOUT"
   "<DEMO_MSG>"
   "DEMO_MSG"
   "<DEMO_ACTIONACTIONRESULT>"
   "DEMO_ACTIONACTIONRESULT"
   "<DEMO_ACTIONGOAL>"
   "DEMO_ACTIONGOAL"
   "<DEMO_ACTIONACTIONGOAL>"
   "DEMO_ACTIONACTIONGOAL"
   "<DEMO_ACTIONRESULT>"
   "DEMO_ACTIONRESULT"
   "<DEMO_ACTIONFEEDBACK>"
   "DEMO_ACTIONFEEDBACK"
   "<DEMO_ACTIONACTION>"
   "DEMO_ACTIONACTION"
   "<DEMO_ACTIONACTIONFEEDBACK>"
   "DEMO_ACTIONACTIONFEEDBACK"
  ))

