// Generated by gencpp from file mastering_ros_demo_pkg/layout.msg
// DO NOT EDIT!


#ifndef MASTERING_ROS_DEMO_PKG_MESSAGE_LAYOUT_H
#define MASTERING_ROS_DEMO_PKG_MESSAGE_LAYOUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mastering_ros_demo_pkg
{
template <class ContainerAllocator>
struct layout_
{
  typedef layout_<ContainerAllocator> Type;

  layout_()
    : label()
    , size(0)
    , stride(0)
    , dataOffset(0)
    , dim()
    , data()  {
    }
  layout_(const ContainerAllocator& _alloc)
    : label(_alloc)
    , size(0)
    , stride(0)
    , dataOffset(0)
    , dim(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;

   typedef int16_t _size_type;
  _size_type size;

   typedef int16_t _stride_type;
  _stride_type stride;

   typedef int16_t _dataOffset_type;
  _dataOffset_type dataOffset;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _dim_type;
  _dim_type dim;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::mastering_ros_demo_pkg::layout_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mastering_ros_demo_pkg::layout_<ContainerAllocator> const> ConstPtr;

}; // struct layout_

typedef ::mastering_ros_demo_pkg::layout_<std::allocator<void> > layout;

typedef boost::shared_ptr< ::mastering_ros_demo_pkg::layout > layoutPtr;
typedef boost::shared_ptr< ::mastering_ros_demo_pkg::layout const> layoutConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mastering_ros_demo_pkg::layout_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mastering_ros_demo_pkg::layout_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mastering_ros_demo_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'mastering_ros_demo_pkg': ['/home/schwarmcyc/Documents/HackMD-tutorial/dit_ws/src/mastering_ros_demo_pkg/msg', '/home/schwarmcyc/Documents/HackMD-tutorial/dit_ws/devel/share/mastering_ros_demo_pkg/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mastering_ros_demo_pkg::layout_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mastering_ros_demo_pkg::layout_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mastering_ros_demo_pkg::layout_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mastering_ros_demo_pkg::layout_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mastering_ros_demo_pkg::layout_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mastering_ros_demo_pkg::layout_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mastering_ros_demo_pkg::layout_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31ed65118d857da3e3032468c31d1183";
  }

  static const char* value(const ::mastering_ros_demo_pkg::layout_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31ed65118d857da3ULL;
  static const uint64_t static_value2 = 0xe3032468c31d1183ULL;
};

template<class ContainerAllocator>
struct DataType< ::mastering_ros_demo_pkg::layout_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mastering_ros_demo_pkg/layout";
  }

  static const char* value(const ::mastering_ros_demo_pkg::layout_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mastering_ros_demo_pkg::layout_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string label\n\
int16 size\n\
int16 stride\n\
int16 dataOffset\n\
int16[] dim\n\
int16[] data\n\
\n\
";
  }

  static const char* value(const ::mastering_ros_demo_pkg::layout_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mastering_ros_demo_pkg::layout_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.size);
      stream.next(m.stride);
      stream.next(m.dataOffset);
      stream.next(m.dim);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct layout_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mastering_ros_demo_pkg::layout_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mastering_ros_demo_pkg::layout_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
    s << indent << "size: ";
    Printer<int16_t>::stream(s, indent + "  ", v.size);
    s << indent << "stride: ";
    Printer<int16_t>::stream(s, indent + "  ", v.stride);
    s << indent << "dataOffset: ";
    Printer<int16_t>::stream(s, indent + "  ", v.dataOffset);
    s << indent << "dim[]" << std::endl;
    for (size_t i = 0; i < v.dim.size(); ++i)
    {
      s << indent << "  dim[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.dim[i]);
    }
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTERING_ROS_DEMO_PKG_MESSAGE_LAYOUT_H
